// Generated by CoffeeScript 1.9.3
(function() {
  var request;

  request = require('request');

  this.key = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_=";

  this.load_card_usages_from_cards = function(main, side) {
    var card_id, count, j, k, last_id, len, len1, result;
    result = [];
    last_id = null;
    for (j = 0, len = main.length; j < len; j++) {
      card_id = main[j];
      if (card_id === last_id) {
        count++;
      } else {
        if (last_id) {
          result.push({
            card_id: last_id,
            side: false,
            count: count
          });
        }
        last_id = card_id;
        count = 1;
      }
    }
    if (last_id) {
      result.push({
        card_id: last_id,
        side: false,
        count: count
      });
    }
    last_id = null;
    for (k = 0, len1 = side.length; k < len1; k++) {
      card_id = side[k];
      if (card_id === last_id) {
        count++;
      } else {
        if (last_id) {
          result.push({
            card_id: last_id,
            side: true,
            count: count
          });
        }
        last_id = card_id;
        count = 1;
      }
    }
    if (last_id) {
      result.push({
        card_id: last_id,
        side: true,
        count: count
      });
    }
    return result;
  };

  this.encode = function(card_usages) {
    var c, card_usage, i, j, k, len, result;
    result = '';
    for (j = 0, len = card_usages.length; j < len; j++) {
      card_usage = card_usages[j];
      c = card_usage.side << 29 | card_usage.count << 27 | card_usage.card_id;
      for (i = k = 4; k >= 0; i = --k) {
        result += this.key.charAt((c >> i * 6) & 0x3F);
      }
    }
    return result;
  };

  this.deck_url = function(name, card_usages, format) {
    return "https://my-card.in/decks/new" + (format ? '.' + format : '') + "?name=" + (encodeURIComponent(name)) + "&cards=" + (this.encode(card_usages));
  };

  this.deck_url_short = function(name, card_usages, callback) {
    request = require('request');
    return request(this.deck_url(name, card_usages, 'short.url'), function(error, response, body) {
      return callback(body);
    });
  };

}).call(this);
