// Generated by CoffeeScript 1.10.0
(function() {
  var User, mongoose, settings;

  settings = require('./config.json');

  mongoose = require('mongoose');

  User = mongoose.model('User', {
    name: String,
    points: Number
  });

  module.exports = User;

}).call(this);

//# sourceMappingURL=user.js.map
